### ISSUE TITLE
Button is always disabled

### ISSUE THREAD

**Issue by ctrl-alt-d** [AvaloniaUI/Documentation#66] opened 2021-08-05 16:28 UTC
Can you bring to me a bit of help, please? This is my first Avalonia UI app ... I'm a bit lost.

My issue is that the button is always disabled:

![Eap Recull_292](https://user-images.githubusercontent.com/3105983/128385016-adb4045b-32e3-46ae-8f99-2d7fddb4c4bf.png)

This is my VM with [`DoTheThing` / `RunTheThing` pattern](https://docs.avaloniaui.net/docs/data-binding/binding-to-commands), look for `HERE!!!` comment in code:

```c#
namespace ER.AvaloniaUI.ViewModels
{
    public class CentresViewModel : ViewModelBase
    {
        private readonly ICentreGetSet BLCentres;
        private readonly ICentreActivaDesactiva BLActivaDesactiva;
        private dtoo.Centre? SelectedItem {
            get; 
            set;
        }
        public CentresViewModel(ICentreGetSet blcentres, ICentreActivaDesactiva blActivaDesactiva)
        {
            BLCentres = blcentres;
            BLActivaDesactiva = blActivaDesactiva;
            DoTheThing = ReactiveCommand.Create( RunTheThing ); // <-- HERE!!!
            RxApp.MainThreadScheduler.Schedule(LoadCentres);    
        }
        public ObservableCollection<dtoo.Centre> MyItems {get;} = new();

        public ReactiveCommand<Unit, Unit> DoTheThing { get; }   // <-- HERE!!!

        void RunTheThing()  // <-- HERE!!!
        {
            if (SelectedItem == null) return;

            //
            var model = (BLActivaDesactiva.Toggle(SelectedItem.Id).GetAwaiter().GetResult()).Data!;
            if (model == null) return;

            //
            var item = MyItems.First(x=>x.Id==model.Id);
            var i = MyItems.IndexOf(item);
            MyItems[i] = model;
        }

        private async void LoadCentres()
        {
            var createParms = new DTO.i.DTOs.EsActiuParms(esActiu: true);
            var l =
                await
                BLCentres
                .GetItems(createParms)
                ;

            l.Data!.ForEach(x=>MyItems.Add(x));
        }
    }
}
```

And there the xaml:

```xml
<UserControl Name="xx"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:viewModels="clr-namespace:ER.AvaloniaUI.ViewModels"
             xmlns:avalonia="clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia"
             xmlns:system="clr-namespace:System;assembly=System.Runtime.Extensions"
             xmlns:styles="clr-namespace:Material.Styles;assembly=Material.Styles"
             xmlns:assists="clr-namespace:Material.Styles.Assists;assembly=Material.Styles"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="ER.AvaloniaUI.Pages.CentresUserCtrl">
    <Design.DataContext>
        <viewModels:CentresViewModel />
    </Design.DataContext>

    <ListBox Items="{Binding MyItems}" SelectedItem="{Binding SelectedItem}">
        <ListBox.ItemTemplate>
            <DataTemplate>
                <Border BorderBrush="Black"
                        BorderThickness="1"
                        CornerRadius="4"
                        Padding="4">
                    <StackPanel Orientation="Horizontal" >
                        <TextBlock Text="{Binding Etiqueta}"/>
                        <TextBlock Text="{Binding EsActiu}"/>
                        <Button Command="{Binding #xx.DoTheThing}">Do the thing! HERE !!!!!!</Button>
                    </StackPanel>                     
                </Border>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
</UserControl>    
```

My goal is to toggle `EsActiu` (is active) bool property on the database model. If this is not the best approach, I'm open to change code for better patterns. Also, I use `ReactiveCommand.Create` instead of `ReactiveCommand.CreateFromTaskp  jut to match documentation patterns.

All code is here:

https://github.com/ctrl-alt-d/eaprecull/tree/issue51/ER.AvaloniaUI

**Comment by MikeCodesDotNET** [comment] 2022-04-28 14:54
Hey, 

You're asking a question more related to your specific application, which might be better handled by our community on [Telegram](https://t.me/Avalonia). That said, I'm happy to point you in the right direction. Typically, if a button isn't enabled, it's usually caused by the command not resolving. I'd check that the ViewModel constructor is actually being invoked as a first step. 

Cheers,
Mike J

**Closed** 2022-04-28 15:01 UTC
