### ISSUE TITLE
UX issue with website migration: google search results linking to dead pages

### ISSUE THREAD

**Issue by binary1230** [AvaloniaUI/Documentation#17] opened 2021-05-22 20:08 UTC
Apologies if this is the wrong place to post this or if you're already aware: just wanted to share some feedback on the docs as a new user learning Avalonia

Right now, google is indexing lots of dead pages for some of the core Avalonia topics, and it slows me down when searching around for reference pages while trying to learn the API.

For instance, if I type in 'Avalonia Binding' into google, I get this as the first result, but it's a 404:
![image](https://user-images.githubusercontent.com/5413064/119239070-8af53d80-bb14-11eb-85d0-03184968929f.png)

It's this page (404):
http://avaloniaui.net/docs/binding/

The correct page (I'm guessing it was moved/etc with the docs migration happening) is here:
https://docs.avaloniaui.net/docs/data-binding

I see it's on nginx, would you consider adding some 301 redirects so it's not as big of a flow stopper when hitting the now-dead URLs? 

Something vaguely like this in nginx.conf might work (definitely double check this before using)
```conf
server {
 listen       80;
 server_name  avaloniaui.net;
 
 location ~ ^/docs/
 {
   return 301 $scheme://docs.avaloniaui.net/docs/$1;
 }
}
```

It's also been a while since I've done this but, if you setup your site in Google Search Console, it should be able to tell you what the most frequent dead links are. If you go to 'Coverage -> Excluded -> 404 not found' it'll tell you what the most commonly hit URLs are.

It's a small thing but would help those of us learning Avalonia bouncing through the docs in frantic google searches : )

Thanks!

**Comment by piksel** [comment] 2021-05-25 12:15
Additionally, the first notice you see in the docs contains a link to the old documentation, which [returns a 403 Forbidden](http://avaloniaui.net/docs/). This is likely the root cause of these issues. The whole old documentation structure seems to have been removed, possibly with the launch of the new site?

As for the new location for the images, I think you need to add them using the GitBooks web UI. The image names currently checked in have [signs of WYSIWYG uploading](https://github.com/AvaloniaUI/Documentation/tree/master/.gitbook/assets).

**Comment by da3dsoul** [comment] 2021-06-20 21:13
This extends further than google (web searching). There are dead links from this pattern change in the docs. An example I found just trying to get started is the link to command bindings in the Button doc.

Current link is http://avaloniaui.net/docs/binding/binding-to-commands
Actual Location is https://docs.avaloniaui.net/docs/data-binding/binding-to-commands

**Comment by kekekeks** [comment] 2021-06-21 07:58
@grokys do we have a full list of links from the previous website? I could setup redirects.

**Comment by piksel** [comment] 2021-06-21 11:49
This is all the references as of 93746cb:

<details>
<summary><code>❯ grep -o -h 'http://avaloniaui.net/[^)]*' -r .</code></summary>

```
http://avaloniaui.net/docs/styles/selectors
http://avaloniaui.net/docs/styles/selectors
http://avaloniaui.net/docs/animations/keyframe#easings
http://avaloniaui.net/docs/styles
http://avaloniaui.net/api/Avalonia.Controls/Border/60DC8BED
http://avaloniaui.net/docs/controls/contentcontrol
http://avaloniaui.net/api/Avalonia.Controls/Button/61B1E7A8
http://avaloniaui.net/api/Avalonia.Controls/Button/7B4CADF5
http://avaloniaui.net/api/Avalonia.Controls/Button/4AAA993D
http://avaloniaui.net/docs/binding/binding-to-commands
http://avaloniaui.net/api/Avalonia.Controls/Button/61B1E7A8
http://avaloniaui.net/api/Avalonia.Input/InputElement/B4FED8A5
http://avaloniaui.net/api/Avalonia.Input/InputElement/0ABE1887
http://avaloniaui.net/api/Avalonia.Controls/Button/#Events
http://avaloniaui.net/api/Avalonia.Controls/Button
http://avaloniaui.net/docs/controls/contentcontrol
http://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756
http://avaloniaui.net/docs/binding
http://avaloniaui.net/docs/templates/datatemplate
http://avaloniaui.net/api/Avalonia.Controls/ContentControl/ACED680E
http://avaloniaui.net/docs/binding/datacontext
http://avaloniaui.net/docs/templates/datatemplate
http://avaloniaui.net/api/Avalonia/AvaloniaProperty/65237C52
http://avaloniaui.net/api/Avalonia.Controls/Button/D29AE9A9
http://avaloniaui.net/docs/quickstart/create-new-project
http://avaloniaui.net/docs/binding/datacontext
http://avaloniaui.net/docs/binding/change-notifications
http://avaloniaui.net/docs/binding/datacontext
http://avaloniaui.net/api/Avalonia.Controls/Window
http://avaloniaui.net/docs/quickstart/create-new-project
http://avaloniaui.net/docs/templates/datatemplate
http://avaloniaui.net/docs/advanced-tutorial/images/rider-welcome.png
http://avaloniaui.net/docs/advanced-tutorial/images/configure-plugin-repos.png
http://avaloniaui.net/docs/advanced-tutorial/images/enter-plugin-repo.png
http://avaloniaui.net/docs/advanced-tutorial/images/plugin-install.png
http://avaloniaui.net/docs/animations/transitions
http://avaloniaui.net/docs/animations/keyframe
http://avaloniaui.net/docs/quickstart/intro-to-xaml
http://avaloniaui.net/docs/advanced/trees
http://avaloniaui.net/docs/quickstart/codebehind
http://avaloniaui.net/docs/quickstart/window
http://avaloniaui.net/docs/quickstart/mvvm
http://avaloniaui.net/docs/binding
http://avaloniaui.net/docs/binding/datacontext
http://avaloniaui.net/docs/binding/bindings
http://avaloniaui.net/docs/binding/binding-to-commands
http://avaloniaui.net/docs/input/images/input-event-routing.png
http://avaloniaui.net/docs/layout/images/layout-margins-padding-alignment-graphic1.png
http://avaloniaui.net/docs/layout/images/layout-margins-padding-alignment-graphic2.png
http://avaloniaui.net/docs/layout/images/layout-horizontal-alignment-graphic.png
http://avaloniaui.net/docs/layout/images/layout-vertical-alignment-graphic.png
http://avaloniaui.net/docs/layout/images/layout-margins-padding-aligment-graphic3.png
http://avaloniaui.net/docs/layout/creating-a-panel
http://avaloniaui.net/docs/layout/alignment-margins-padding
http://avaloniaui.net/docs/layout/panels-overview
http://avaloniaui.net/docs/layout/alignment-margins-padding
http://avaloniaui.net/docs/layout/creating-a-panel
http://avaloniaui.net/docs/styles/styles
http://avaloniaui.net/docs/quickstart/assets
http://avaloniaui.net/docs/styles/selectors#is
http://avaloniaui.net/api/Avalonia.Controls/Control/580076CD
http://avaloniaui.net/docs/styles/selectors#ofType
http://avaloniaui.net/api/Avalonia/StyledElement/0A46A84A
http://avaloniaui.net/api/Avalonia/Application/04017CAF
http://avaloniaui.net/docs/quickstart/assets
http://avaloniaui.net/docs/styles/selectors
http://avaloniaui.net/api/Avalonia.Controls.Templates/FuncDataTemplate_1/
http://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756
http://avaloniaui.net/docs/controls/contentcontrol
http://avaloniaui.net/docs/templates/images/hello-world-button.png
http://avaloniaui.net/docs/templates/images/hello-world-string.png
http://avaloniaui.net/docs/templates/images/student-no-datatemplate.png
http://avaloniaui.net/api/Avalonia.Controls/ContentControl/7AA9343E
http://avaloniaui.net/docs/templates/images/student-first-last-name.png
http://avaloniaui.net/docs/window
http://avaloniaui.net/docs/usercontrol
http://avaloniaui.net/docs/quickstart/images/codebehind-vs.png
http://avaloniaui.net/docs/quickstart/devtools
http://avaloniaui.net/api/Avalonia.Controls/Window/
http://avaloniaui.net/docs/quickstart/codebehind
http://avaloniaui.net/docs/controls
http://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756
http://avaloniaui.net/docs/binding
http://avaloniaui.net/docs/quickstart/codebehind
http://avaloniaui.net/docs/binding/bindings
http://avaloniaui.net/docs/quickstart/codebehind
http://avaloniaui.net/docs/quickstart/window
http://avaloniaui.net/docs/quickstart/usercontrol
http://avaloniaui.net/docs/quickstart/images/mvvm.png
http://avaloniaui.net/docs/quickstart/packages
http://avaloniaui.net/docs/tutorial/
http://avaloniaui.net/docs/reactiveui/activation
http://avaloniaui.net/docs/reactiveui/routing
http://avaloniaui.net/docs/reactiveui/suspension
http://avaloniaui.net/docs/reactiveui/activation
http://avaloniaui.net/images/docs/routing.gif
http://avaloniaui.net/docs/authoring-controls/defining-properties
http://avaloniaui.net/docs/binding/binding-from-code#subscribing-to-a-property-on-any-object
http://avaloniaui.net/docs/styles/styles
http://avaloniaui.net/docs#
http://avaloniaui.net/support
http://avaloniaui.net/docs/advanced-tutorial/images/buy-button.png
http://avaloniaui.net/docs/advanced-tutorial/images/add-styles.png
http://avaloniaui.net/docs/advanced-tutorial/images/pretty-button.png
http://avaloniaui.net/docs/advanced-tutorial/images/text-list.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310010932979.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310011526700.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310175949319.png
http://avaloniaui.net/docs/advanced-tutorial/images/dark-mode-preview.png
http://avaloniaui.net/docs/advanced-tutorial/images/acrylic-material.png
http://avaloniaui.net/docs/advanced-tutorial/images/full-acrylic-window.png
http://avaloniaui.net/docs/advanced-tutorial/images/CreateSolution.png
http://avaloniaui.net/docs/advanced-tutorial/images/project-structure.png
http://avaloniaui.net/docs/advanced-tutorial/images/debug-button.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310192926578.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310173858088.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310184202271.png
http://avaloniaui.net/docs/advanced-tutorial/images/add-window.png
http://avaloniaui.net/docs/advanced-tutorial/images/dialog-opened.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310184538120.png
http://avaloniaui.net/docs/advanced-tutorial/images/mvvm.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310013703557.png
http://avaloniaui.net/docs/advanced-tutorial/images/image-20210310110401944.png
http://avaloniaui.net/docs/advanced-tutorial/images/rider-welcome.png
http://avaloniaui.net/docs/advanced-tutorial/images/configure-plugin-repos.png
http://avaloniaui.net/docs/advanced-tutorial/images/enter-plugin-repo.png
http://avaloniaui.net/docs/advanced-tutorial/images/plugin-install.png
http://avaloniaui.net/docs/tutorial/creating-a-view#create-the-usercontrol
http://avaloniaui.net/docs/tutorial/images/adding-new-items-view.png
http://avaloniaui.net/docs/binding/change-notifications
http://avaloniaui.net/docs/tutorial/images/adding-new-item-run.gif
http://avaloniaui.net/docs/binding/binding-to-commands
http://avaloniaui.net/docs/binding/change-notifications
http://avaloniaui.net/docs/tutorial/adding-new-items#swap-out-the-list-view-model
http://avaloniaui.net/docs/tutorial/images/adding-new-items-2-run.gif
http://avaloniaui.net/docs/quickstart/intro-to-xaml#xaml-or-axaml-file
http://avaloniaui.net/docs/tutorial/images/creating-a-view-todolistview.png
http://avaloniaui.net/docs/tutorial/images/creating-a-view-run.png
http://avaloniaui.net/docs/tutorial/wiring-up-views#update-mainwindow
http://avaloniaui.net/docs/templates/datatemplate
http://avaloniaui.net/docs/controls/contentcontrol
http://avaloniaui.net/docs/quickstart/mvvm
http://avaloniaui.net/docs/binding
http://avaloniaui.net/docs/binding/bindings
http://avaloniaui.net/docs/tutorial/creating-model-viewmodel#create-an-instance-of-todolistviewmodel
http://avaloniaui.net/docs/tutorial/creating-a-view#display-the-view-in-the-window
http://avaloniaui.net/docs/templates/datatemplate
http://avaloniaui.net/docs/tutorial/images/wiring-up-views-run.png
```

</details>

There are currently three PRs with dead link fixes. I have a 4th including all missing images but I didn't create it due to the lack of response in those...

**Closed** 2023-06-28 05:01 UTC
Labels: docs experience, dead link
